# Generated by Django 2.0.5 on 2018-05-06 23:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='account', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('picture', models.ImageField(null=True, upload_to='account')),
                ('balance', models.IntegerField()),
                ('interests', models.ManyToManyField(to='category.Category')),
            ],
        ),
    ]
