# Generated by Django 2.0.5 on 2018-05-14 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20180507_0559'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='telephone',
            field=models.BigIntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='picture',
            field=models.ImageField(default='account/default_profile.jpg', upload_to='account'),
        ),
    ]
