# Generated by Django 2.0.5 on 2018-05-14 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20180514_2331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='telephone',
        ),
    ]
