# Generated by Django 2.0.5 on 2018-05-14 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_account_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='telephone',
            field=models.BigIntegerField(default=0),
        ),
    ]
