# Generated by Django 2.0.5 on 2018-05-07 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
