# Generated by Django 2.0.5 on 2018-05-07 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0002_auto_20180507_0635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='picture',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='campaign'),
        ),
    ]
