# Generated by Django 2.0.5 on 2018-05-07 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0003_auto_20180507_0638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
