# Generated by Django 2.0.5 on 2018-05-14 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0005_auto_20180507_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='category.Category'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='picture',
            field=models.ImageField(default='default.jpg', upload_to='campaign'),
        ),
    ]
